site_name: Robot Builders Notes

# In mkdocs.yml, confirm this setting is correct:
docs_dir: 'docs'

theme: readthedocs

# override what is found with specific files
nav:
  - Home: index.md
  
  - Sensors:
    - Overview: Sensors/00-sensors-overview.md
    - Micromouse:
      - Emitters: Sensors/20-10-sensors.md
      - Detectors: Sensors/20-10-sensors.md
      - Constant Current Drive: Sensors/20-30-constant-current-drive.md
    - Line Followers:
       - Line Sensing: Sensors/30-10-line-followers.md
       - Marker Sensing: Sensors/30-10-line-followers.md
    - Encoders:
      - Overview: Authors/template.md
      - Implementation: Authors/template.md # Changed 'Encoders' to 'Implementation' for clarity
    - IMUs:
      - Overview: Sensors/30-30-imus.md
      - Implementation: Authors/template.md # Changed 'IMUs' to 'Implementation' for clarity

  - Motors: # Included the commented-out section for completeness
    - Overview: Motors/30-00-motors.md
    - DC Brush: Motors/30-20-dc-brushed.md
    - DC Brushless: Motors/30-30-dc-brushless.md
    - Stepper:  Motors/30-40-steppers.md
    
  - User Guide:
    - Writing your docs: Authors/writing-your-docs.md
    - Styling your docs: Authors/styling-your-docs.md
    - Maths Rendering: Authors/mathjax.md

  - About:
    - License: license.md
    - Release Notes: release-notes.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxhelper.js

markdown_extensions:
    - toc:
        permalink: true
    - extra
    - tables
    - fenced_code 