name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger build on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip' # Cache dependencies for faster builds

      - name: Install MkDocs and dependencies
        run: pip install -r requirements.txt
        
      - name: Deploy MkDocs to GitHub Pages
        # The 'mkdocs gh-deploy --force' command builds the site 
        # and pushes the resulting static files to the 'gh-pages' branch.
        run: mkdocs gh-deploy --force
        